# Customer Churn Prediction using ANN

In [4]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from numpy.ma.core import shape

In [5]:
df=pd.read_csv('Churn_Modelling.csv')

In [6]:
df.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [7]:
df.shape

(10000, 14)

In [8]:
# what we can remove
# row number , creditscore

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   RowNumber        10000 non-null  int64
 1   CustomerId       10000 non-null  int64
 2   Surname          10000 non-null  object
 3   CreditScore      10000 non-null  int64
 4   Geography        10000 non-null  object
 5   Gender           10000 non-null  object
 6   Age              10000 non-null  int64
 7   Tenure           10000 non-null  int64
 8   Balance          10000 non-null  float64
 9   NumOfProducts    10000 non-null  int64
 10  HasCrCard        10000 non-null  int64
 11  IsActiveMember   10000 non-null  int64
 12  EstimatedSalary  10000 non-null  float64
 13  Exited           10000 non-null  int64
dtypes: float64(2), int64(9), object(3)
memory usage: 1.1+ MB

In [10]:
# THE DATASET IS COMPLETE

In [11]:
df.duplicated().sum()

np.int64(0)

In [12]:
df['Exited'].value_counts()

Exited
0    7963
1    2037
Name: count, dtype: int64

In [13]:
df['Geography'].value_counts()

Geography
France     5014
Germany    2509
Spain      2477
Name: count, dtype: int64

In [14]:
df['Gender'].value_counts()

Gender
Male      5457
Female    4543
Name: count, dtype: int64

In [15]:
df.drop(columns=['RowNumber','CustomerId','Surname'],inplace=True)

In [16]:
df.head()

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [17]:
# pd.get_dummies(df,columns=['Geography','Gender'],drop_first=False)
# X=df.drop('Exited',axis=1)
# y=df['Exited']

In [18]:
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

In [19]:
X=df.drop('Exited',axis=1)
y=df['Exited']

In [20]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

In [21]:
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline

# Define which columns are numerical and which are categorical
numerical_cols = ['CreditScore', 'Age', 'Tenure', 'Balance', 'NumOfProducts', 'HasCrCard',
                 'IsActiveMember', 'EstimatedSalary']
categorical_cols = ['Geography', 'Gender']

# Create a column transformer
preprocessor = ColumnTransformer(
    transformers=[
        ('num', StandardScaler(), numerical_cols),
        ('cat', OneHotEncoder(), categorical_cols)
    ])

# Apply the transformations to the training data
X_train_scaled = preprocessor.fit_transform(X_train)
X_test_scaled = preprocessor.transform(X_test)

In [22]:
print(f"Number of features after preprocessing: {X_train_scaled.shape[1]}")

Number of features after preprocessing: 13

In [23]:
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Dense

D:\Deep Learning 2 (Final)\.venv\Lib\site-packages\keras\src\export\tf2onnx_lib.py:8: FutureWarning: In the future `np.object` will be defined as the corresponding NumPy scalar.
  if not hasattr(np, "object"):

In [35]:
model=Sequential()

model.add(Dense(3,activation='relu',input_dim=13))
model.add(Dense(1,activation='relu'))

D:\Deep Learning 2 (Final)\.venv\Lib\site-packages\keras\src\layers\core\dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [36]:
model.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_2 (Dense)                 │ (None, 3)              │            42 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_3 (Dense)                 │ (None, 1)              │             4 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 46 (184.00 B)

 Trainable params: 46 (184.00 B)

 Non-trainable params: 0 (0.00 B)

In [37]:
model.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])

In [45]:
model.fit(X_train_scaled,y_train,epochs=100,validation_split=0.2)

Epoch 1/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8420 - loss: 0.3674 - val_accuracy: 0.8431 - val_loss: 0.3621
Epoch 2/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 934us/step - accuracy: 0.8408 - loss: 0.3670 - val_accuracy: 0.8438 - val_loss: 0.3637
Epoch 3/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 943us/step - accuracy: 0.8391 - loss: 0.3660 - val_accuracy: 0.8419 - val_loss: 0.3627
Epoch 4/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 946us/step - accuracy: 0.8414 - loss: 0.3666 - val_accuracy: 0.8413 - val_loss: 0.3635
Epoch 5/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 909us/step - accuracy: 0.8414 - loss: 0.3655 - val_accuracy: 0.8419 - val_loss: 0.3633
Epoch 6/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 893us/step - accuracy: 0.8408 - loss: 0.3652 - val_accuracy: 0.8419 - val_loss: 0.3632
Epoch 7/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 897us/step - accuracy: 0.8402 - loss: 0.3665 - val_accuracy: 0.8388 - val_loss: 0.3667
Epoch 8/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 901us/step - accuracy: 0.8394 - loss: 0.3659 - val_accuracy: 0.8419 - val_loss: 0.3647
Epoch 9/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 904us/step - accuracy: 0.8414 - loss: 0.3654 - val_accuracy: 0.8406 - val_loss: 0.3642
Epoch 10/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 953us/step - accuracy: 0.8409 - loss: 0.3652 - val_accuracy: 0.8419 - val_loss: 0.3643
Epoch 11/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 930us/step - accuracy: 0.8413 - loss: 0.3654 - val_accuracy: 0.8419 - val_loss: 0.3658
Epoch 12/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 898us/step - accuracy: 0.8400 - loss: 0.3652 - val_accuracy: 0.8400 - val_loss: 0.3649
Epoch 13/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 927us/step - accuracy: 0.8419 - loss: 0.3651 - val_accuracy: 0.8413 - val_loss: 0.3650
Epoch 14/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 935us/step - accuracy: 0.8405 - loss: 0.3651 - val_accuracy: 0.8406 - val_loss: 0.3650
Epoch 15/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 911us/step - accuracy: 0.8389 - loss: 0.3669 - val_accuracy: 0.8400 - val_loss: 0.3654
Epoch 16/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 891us/step - accuracy: 0.8405 - loss: 0.3674 - val_accuracy: 0.8419 - val_loss: 0.3667
Epoch 17/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 902us/step - accuracy: 0.8400 - loss: 0.3653 - val_accuracy: 0.8406 - val_loss: 0.3658
Epoch 18/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 903us/step - accuracy: 0.8397 - loss: 0.3651 - val_accuracy: 0.8406 - val_loss: 0.3664
Epoch 19/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 940us/step - accuracy: 0.8400 - loss: 0.3652 - val_accuracy: 0.8413 - val_loss: 0.3652
Epoch 20/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 919us/step - accuracy: 0.8397 - loss: 0.3653 - val_accuracy: 0.8419 - val_loss: 0.3655
Epoch 21/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 897us/step - accuracy: 0.8386 - loss: 0.3650 - val_accuracy: 0.8406 - val_loss: 0.3661
Epoch 22/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 892us/step - accuracy: 0.8397 - loss: 0.3649 - val_accuracy: 0.8413 - val_loss: 0.3650
Epoch 23/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 915us/step - accuracy: 0.8403 - loss: 0.3653 - val_accuracy: 0.8425 - val_loss: 0.3656
Epoch 24/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 916us/step - accuracy: 0.8403 - loss: 0.3650 - val_accuracy: 0.8419 - val_loss: 0.3665
Epoch 25/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 926us/step - accuracy: 0.8402 - loss: 0.3655 - val_accuracy: 0.8419 - val_loss: 0.3659
Epoch 26/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 910us/step - accuracy: 0.8409 - loss: 0.3649 - val_accuracy: 0.8425 - val_loss: 0.3658
Epoch 27/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 983us/step - accuracy: 0.8406 - loss: 0.3652 - val_accuracy: 0.8431 - val_loss: 0.3669
Epoch 28/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 924us/step - accuracy: 0.8398 - loss: 0.3653 - val_accuracy: 0.8419 - val_loss: 0.3652
Epoch 29/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 927us/step - accuracy: 0.8388 - loss: 0.3652 - val_accuracy: 0.8431 - val_loss: 0.3663
Epoch 30/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 951us/step - accuracy: 0.8372 - loss: 0.3680 - val_accuracy: 0.8344 - val_loss: 0.3716
Epoch 31/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 918us/step - accuracy: 0.8370 - loss: 0.3676 - val_accuracy: 0.8381 - val_loss: 0.3689
Epoch 32/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 914us/step - accuracy: 0.8384 - loss: 0.3665 - val_accuracy: 0.8394 - val_loss: 0.3681
Epoch 33/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 903us/step - accuracy: 0.8388 - loss: 0.3660 - val_accuracy: 0.8406 - val_loss: 0.3665
Epoch 34/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 905us/step - accuracy: 0.8398 - loss: 0.3655 - val_accuracy: 0.8406 - val_loss: 0.3657
Epoch 35/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 912us/step - accuracy: 0.8400 - loss: 0.3652 - val_accuracy: 0.8413 - val_loss: 0.3667
Epoch 36/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 916us/step - accuracy: 0.8405 - loss: 0.3650 - val_accuracy: 0.8400 - val_loss: 0.3660
Epoch 37/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 921us/step - accuracy: 0.8406 - loss: 0.3650 - val_accuracy: 0.8406 - val_loss: 0.3659
Epoch 38/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 889us/step - accuracy: 0.8411 - loss: 0.3651 - val_accuracy: 0.8419 - val_loss: 0.3652
Epoch 39/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 922us/step - accuracy: 0.8394 - loss: 0.3648 - val_accuracy: 0.8413 - val_loss: 0.3653
Epoch 40/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 907us/step - accuracy: 0.8403 - loss: 0.3646 - val_accuracy: 0.8419 - val_loss: 0.3650
Epoch 41/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 900us/step - accuracy: 0.8398 - loss: 0.3650 - val_accuracy: 0.8413 - val_loss: 0.3662
Epoch 42/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 905us/step - accuracy: 0.8402 - loss: 0.3647 - val_accuracy: 0.8413 - val_loss: 0.3658
Epoch 43/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 927us/step - accuracy: 0.8397 - loss: 0.3649 - val_accuracy: 0.8413 - val_loss: 0.3651
Epoch 44/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 933us/step - accuracy: 0.8392 - loss: 0.3646 - val_accuracy: 0.8406 - val_loss: 0.3661
Epoch 45/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 903us/step - accuracy: 0.8408 - loss: 0.3647 - val_accuracy: 0.8419 - val_loss: 0.3649
Epoch 46/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 896us/step - accuracy: 0.8413 - loss: 0.3651 - val_accuracy: 0.8406 - val_loss: 0.3655
Epoch 47/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 899us/step - accuracy: 0.8405 - loss: 0.3645 - val_accuracy: 0.8413 - val_loss: 0.3656
Epoch 48/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 891us/step - accuracy: 0.8398 - loss: 0.3652 - val_accuracy: 0.8406 - val_loss: 0.3648
Epoch 49/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 912us/step - accuracy: 0.8395 - loss: 0.3651 - val_accuracy: 0.8419 - val_loss: 0.3652
Epoch 50/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 889us/step - accuracy: 0.8402 - loss: 0.3648 - val_accuracy: 0.8406 - val_loss: 0.3658
Epoch 51/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 926us/step - accuracy: 0.8398 - loss: 0.3652 - val_accuracy: 0.8413 - val_loss: 0.3663
Epoch 52/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 922us/step - accuracy: 0.8408 - loss: 0.3647 - val_accuracy: 0.8406 - val_loss: 0.3651
Epoch 53/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 930us/step - accuracy: 0.8403 - loss: 0.3650 - val_accuracy: 0.8406 - val_loss: 0.3644
Epoch 54/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 926us/step - accuracy: 0.8394 - loss: 0.3651 - val_accuracy: 0.8413 - val_loss: 0.3657
Epoch 55/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 893us/step - accuracy: 0.8405 - loss: 0.3651 - val_accuracy: 0.8419 - val_loss: 0.3660
Epoch 56/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 893us/step - accuracy: 0.8402 - loss: 0.3650 - val_accuracy: 0.8425 - val_loss: 0.3657
Epoch 57/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 908us/step - accuracy: 0.8413 - loss: 0.3651 - val_accuracy: 0.8413 - val_loss: 0.3654
Epoch 58/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 902us/step - accuracy: 0.8406 - loss: 0.3651 - val_accuracy: 0.8425 - val_loss: 0.3668
Epoch 59/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 931us/step - accuracy: 0.8397 - loss: 0.3652 - val_accuracy: 0.8413 - val_loss: 0.3651
Epoch 60/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 923us/step - accuracy: 0.8402 - loss: 0.3648 - val_accuracy: 0.8406 - val_loss: 0.3650
Epoch 61/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 908us/step - accuracy: 0.8391 - loss: 0.3652 - val_accuracy: 0.8413 - val_loss: 0.3645
Epoch 62/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 906us/step - accuracy: 0.8397 - loss: 0.3660 - val_accuracy: 0.8413 - val_loss: 0.3664
Epoch 63/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 920us/step - accuracy: 0.8403 - loss: 0.3651 - val_accuracy: 0.8406 - val_loss: 0.3654
Epoch 64/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 917us/step - accuracy: 0.8400 - loss: 0.3648 - val_accuracy: 0.8413 - val_loss: 0.3648
Epoch 65/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 912us/step - accuracy: 0.8408 - loss: 0.3647 - val_accuracy: 0.8425 - val_loss: 0.3673
Epoch 66/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 922us/step - accuracy: 0.8416 - loss: 0.3668 - val_accuracy: 0.8438 - val_loss: 0.3650
Epoch 67/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 923us/step - accuracy: 0.8372 - loss: 0.3821 - val_accuracy: 0.8300 - val_loss: 0.4463
Epoch 68/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 900us/step - accuracy: 0.8341 - loss: 0.3897 - val_accuracy: 0.8350 - val_loss: 0.3729
Epoch 69/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 956us/step - accuracy: 0.8361 - loss: 0.3702 - val_accuracy: 0.8356 - val_loss: 0.3715
Epoch 70/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8370 - loss: 0.3676 - val_accuracy: 0.8363 - val_loss: 0.3703
Epoch 71/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8378 - loss: 0.3670 - val_accuracy: 0.8369 - val_loss: 0.3693
Epoch 72/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8377 - loss: 0.3665 - val_accuracy: 0.8369 - val_loss: 0.3684
Epoch 73/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 976us/step - accuracy: 0.8386 - loss: 0.3663 - val_accuracy: 0.8381 - val_loss: 0.3677
Epoch 74/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8381 - loss: 0.3659 - val_accuracy: 0.8388 - val_loss: 0.3677
Epoch 75/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8380 - loss: 0.3657 - val_accuracy: 0.8413 - val_loss: 0.3676
Epoch 76/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 961us/step - accuracy: 0.8397 - loss: 0.3654 - val_accuracy: 0.8413 - val_loss: 0.3667
Epoch 77/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 937us/step - accuracy: 0.8400 - loss: 0.3654 - val_accuracy: 0.8419 - val_loss: 0.3668
Epoch 78/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8409 - loss: 0.3650 - val_accuracy: 0.8419 - val_loss: 0.3665
Epoch 79/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8411 - loss: 0.3651 - val_accuracy: 0.8413 - val_loss: 0.3660
Epoch 80/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8402 - loss: 0.3649 - val_accuracy: 0.8413 - val_loss: 0.3658
Epoch 81/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8394 - loss: 0.3647 - val_accuracy: 0.8419 - val_loss: 0.3656
Epoch 82/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8405 - loss: 0.3649 - val_accuracy: 0.8400 - val_loss: 0.3658
Epoch 83/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8402 - loss: 0.3647 - val_accuracy: 0.8419 - val_loss: 0.3652
Epoch 84/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8395 - loss: 0.3646 - val_accuracy: 0.8419 - val_loss: 0.3654
Epoch 85/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8405 - loss: 0.3648 - val_accuracy: 0.8419 - val_loss: 0.3660
Epoch 86/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8400 - loss: 0.3647 - val_accuracy: 0.8413 - val_loss: 0.3662
Epoch 87/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 972us/step - accuracy: 0.8403 - loss: 0.3646 - val_accuracy: 0.8419 - val_loss: 0.3658
Epoch 88/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 987us/step - accuracy: 0.8398 - loss: 0.3646 - val_accuracy: 0.8413 - val_loss: 0.3656
Epoch 89/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8402 - loss: 0.3644 - val_accuracy: 0.8413 - val_loss: 0.3670
Epoch 90/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 989us/step - accuracy: 0.8395 - loss: 0.3647 - val_accuracy: 0.8406 - val_loss: 0.3659
Epoch 91/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.8402 - loss: 0.3645 - val_accuracy: 0.8406 - val_loss: 0.3656
Epoch 92/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8398 - loss: 0.3647 - val_accuracy: 0.8413 - val_loss: 0.3661
Epoch 93/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 995us/step - accuracy: 0.8402 - loss: 0.3650 - val_accuracy: 0.8419 - val_loss: 0.3659
Epoch 94/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8402 - loss: 0.3650 - val_accuracy: 0.8400 - val_loss: 0.3653
Epoch 95/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8398 - loss: 0.3645 - val_accuracy: 0.8413 - val_loss: 0.3665
Epoch 96/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 967us/step - accuracy: 0.8403 - loss: 0.3650 - val_accuracy: 0.8413 - val_loss: 0.3655
Epoch 97/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 938us/step - accuracy: 0.8402 - loss: 0.3648 - val_accuracy: 0.8425 - val_loss: 0.3646
Epoch 98/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8414 - loss: 0.3651 - val_accuracy: 0.8406 - val_loss: 0.3653
Epoch 99/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - accuracy: 0.8395 - loss: 0.3651 - val_accuracy: 0.8419 - val_loss: 0.3655
Epoch 100/100
200/200 ━━━━━━━━━━━━━━━━━━━━ 0s 970us/step - accuracy: 0.8389 - loss: 0.3650 - val_accuracy: 0.8419 - val_loss: 0.3662

In [46]:
model.layers[1].get_weights()

[array([[0.10318761],
        [0.3684955 ],
        [0.35345232]], dtype=float32),
 array([0.01639078], dtype=float32)]

In [47]:
model.predict(X_test_scaled)

63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 527us/step

array([[0.06288403],
       [0.01639078],
       [0.12031201],
       ...,
       [0.5029688 ],
       [0.2120777 ],
       [0.2534677 ]], shape=(2000, 1), dtype=float32)

In [48]:
y_log=model.predict(X_test_scaled)

63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 529us/step

In [49]:

y_pred=np.where(y_log>0.5,1,0)

In [50]:
from sklearn.metrics import accuracy_score

In [51]:
accuracy_score(y_test,y_pred)

0.846